# Generated by Django 4.2.7 on 2025-09-30 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimerSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "work_duration",
                    models.IntegerField(
                        default=25, help_text="Work session duration in minutes"
                    ),
                ),
                (
                    "short_break_duration",
                    models.IntegerField(
                        default=5, help_text="Short break duration in minutes"
                    ),
                ),
                (
                    "long_break_duration",
                    models.IntegerField(
                        default=15, help_text="Long break duration in minutes"
                    ),
                ),
                (
                    "auto_start_breaks",
                    models.BooleanField(
                        default=False, help_text="Automatically start break timers"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User these settings belong to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timer_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Timer Settings",
                "verbose_name_plural": "Timer Settings",
            },
        ),
        migrations.CreateModel(
            name="TimerSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task",
                    models.TextField(help_text="Description of what you're working on"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional notes about the task",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When the session started",
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the session completed/stopped",
                        null=True,
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        default=0, help_text="Total seconds worked (excluding pauses)"
                    ),
                ),
                (
                    "pause_duration",
                    models.IntegerField(default=0, help_text="Total seconds paused"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("stopped", "Stopped"),
                        ],
                        db_index=True,
                        default="running",
                        help_text="Current session status",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who owns this session",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timer_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Timer Session",
                "verbose_name_plural": "Timer Sessions",
                "ordering": ["-start_time"],
                "indexes": [
                    models.Index(
                        fields=["created_by", "status"],
                        name="task_timer__created_9f980f_idx",
                    ),
                    models.Index(
                        fields=["created_by", "start_time"],
                        name="task_timer__created_3acd7b_idx",
                    ),
                ],
            },
        ),
    ]
